workflows:
  flutter-ios-build:
    name: Flutter iOS CI/CD
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app-store-connect  # Contains API credentials
    scripts:
      - name: Install Flutter dependencies
        script: |
          cd jagruti_app
          flutter pub get

      - name: Initialize keychain
        script: |
          keychain initialize

      - name: Fetch signing assets
        script: |
          app-store-connect fetch-signing-files "com.aaryalabs.jagrutiApp" \
            --type IOS_APP_STORE \
            --create

      - name: Install certificates
        script: |
          keychain add-certificates

      - name: Build and sign IPA
        script: |
          cd jagruti_app
          flutter build ipa --release \
            --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_driver/**/outputs/**/*.json  # Optional test reports

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY  # Critical: Must use PRIVATE_KEY
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id: $APP_STORE_CONNECT_KEY_ID
        submit_to_testflight: true  # Explicitly enable TestFlight submission
      email:
        recipients:
          - kunalgujar.bugs@gmail.com
        notify:
          success: true
          failure: true