workflows:
  flutter-ios-build:
    name: Flutter iOS CI/CD
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app-store-connect  # Codemagic code signing credentials
    scripts:
      - name: Install Flutter dependencies
        script: |
          cd jagruti_app
          flutter pub get

      - name: Initialize keychain and install signing certificates
        script: |
          keychain initialize
          keychain add-certificates

      - name: Install CocoaPods dependencies
        script: |
          cd jagruti_app/ios
          pod install

      - name: Build Flutter iOS app (no codesign)
        script: |
          cd jagruti_app
          flutter build ios --release --no-codesign

      - name: Apply provisioning profiles and sign the app
        script: |
          xcode-project use-profiles
          xcode-project build-ipa \
            --workspace jagruti_app/ios/Runner.xcworkspace \
            --scheme Runner

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - kunalgujar.bugs@gmail.com
        notify:
          success: true
          failure: true