workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: |
          cd jagruti_app
          flutter pub get
      - name: Build iOS release
        script: |
          cd jagruti_app
          flutter build ios --release --no-codesign
    artifacts:
      - jagruti_app/build/ios/iphoneos/*.app
      - jagruti_app/build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - kunalgujar.bugs@gmail.com